# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelaprincipal.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnNovoCliente = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovoCliente.setGeometry(QtCore.QRect(20, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnNovoCliente.setFont(font)
        self.btnNovoCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnNovoCliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnNovoCliente.setStyleSheet("Text-align:center")
        self.btnNovoCliente.setObjectName("btnNovoCliente")
        self.btnListarClientes = QtWidgets.QPushButton(self.centralwidget)
        self.btnListarClientes.setGeometry(QtCore.QRect(180, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnListarClientes.setFont(font)
        self.btnListarClientes.setObjectName("btnListarClientes")
        self.btnEditarDados = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditarDados.setGeometry(QtCore.QRect(250, 430, 101, 31))
        self.btnEditarDados.setObjectName("btnEditarDados")
        self.btnAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizar.setGeometry(QtCore.QRect(80, 430, 101, 31))
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.btnDelCliente = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelCliente.setGeometry(QtCore.QRect(420, 430, 91, 31))
        self.btnDelCliente.setObjectName("btnDelCliente")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 561, 361))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(7)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(181)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setDefaultSectionSize(37)
        self.tableWidget.verticalHeader().setMinimumSectionSize(37)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNovoCliente.setText(_translate("MainWindow", "Novo cliente"))
        self.btnListarClientes.setText(_translate("MainWindow", "Listar serviços"))
        self.btnEditarDados.setText(_translate("MainWindow", "Editar dados"))
        self.btnAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.btnDelCliente.setText(_translate("MainWindow", "Deletar cliente"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "col1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "col2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
